# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value



services:
    app.doctrine.entity_listener_resolver:
        class: AppBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]

    twig.extension.app:
        class: AppBundle\Twig\AppExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    issue.listener:
        class: AppBundle\Listener\IssueListener
        arguments: [@app.mailer]
        tags:
            -  { name: doctrine.entity_listener }
    app.mailer:
        class: AppBundle\Service\MailerService
        arguments: [@doctrine.orm.entity_manager, @mailer, @security.token_storage, @templating, %mailer_send_from_email%]