issuetype:
    path:     /
    defaults: { _controller: "AppBundle:IssueType:index" }

issuetype_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:IssueType:show" }

issuetype_new:
    path:     /new
    defaults: { _controller: "AppBundle:IssueType:new" }

issuetype_create:
    path:     /create
    defaults: { _controller: "AppBundle:IssueType:create" }
    methods:  POST

issuetype_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:IssueType:edit" }

issuetype_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:IssueType:update" }
    methods:  [POST, PUT]

issuetype_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:IssueType:delete" }
    methods:  [POST, DELETE]
