priority:
    path:     /
    defaults: { _controller: "AppBundle:Priority:index" }

priority_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Priority:show" }

priority_new:
    path:     /new
    defaults: { _controller: "AppBundle:Priority:new" }

priority_create:
    path:     /create
    defaults: { _controller: "AppBundle:Priority:create" }
    methods:  POST

priority_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Priority:edit" }

priority_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Priority:update" }
    methods:  [POST, PUT]

priority_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Priority:delete" }
    methods:  [POST, DELETE]
